// @ts-nocheck
/**
 * apps/api/src/product/sub_category/SubCategory.types.ts
 *
 * Source-verified types for the SubCategory module. Mirrors, field-for-field:
 *  - com.bloomscorp.loom.product.sub_category.orm.SubCategory          (extends BehemothORM, implements Cloneable)
 *  - com.bloomscorp.loom.product.sub_category.orm.SubCategoryPreview   (same physical table, projected fields)
 *  - com.bloomscorp.loom.product.sub_category.pojo.SubCategoryData
 *  - com.bloomscorp.loom.product.sub_category.pojo.FeaturedSubcategory
 *
 * ============================================================================
 * SCHEMA GAP — FLAGGED, NOT SILENTLY DROPPED
 * ============================================================================
 * The Java `SubCategory` entity declares two real, persisted columns that do
 * NOT exist on `sub_category` in the introspected schema
 * (`apps/api/src/database/schema/schema.ts`, generated by `pnpm db:introspect`
 * from the live DB):
 *
 *   - avgWorkHoursPerMeter (NUMERIC, nullable)
 *   - impactConfigVersion  (INTEGER, NOT NULL, default 1)
 *
 * This is independently corroborated by the Java side itself:
 * `SubCategoryData` (the native-query projection pojo) and
 * `SubCategoryNativeQuery.RETRIEVE_SUB_CATEGORY(_BY_ID)` both omit these two
 * columns from their SELECT list — so even the existing Java table-explorer
 * path never round-trips them either. Whatever migration added these two
 * Java-entity fields has evidently not been applied against `loom-local-db`
 * yet (or was rolled back).
 *
 * Decision: keep both fields on the API-facing types (so the `impactConfigVersion`
 * bump computation in SubCategory.service.ts can still be reasoned about and a
 * future migration slots in cleanly), but the repository/mapper CANNOT write
 * columns that don't exist — `SubCategory.repository.ts` does not reference
 * either field. Flagged again at the write site. A real DB migration adding
 * these two columns is required before this parity gap can close.
 *
 * `@anuprerna/types` is currently an empty workspace stub and the project has
 * no zod (or any validation library) dependency, so these are plain TS types
 * with hand-written runtime guards in SubCategory.dto.ts, exactly like
 * SkuGroup.types.ts / commerce/cart/types/cart.types.ts.
 */

/**
 * Generic file-upload representation for the three MultipartFile fields on
 * the Java entity (iconFile, socialImageFile, featuredImageFile). Kept local
 * and framework-agnostic rather than importing a multer type, since the
 * controller (which would own the actual multipart parsing) is out of scope
 * for this checkpoint.
 */
export interface UploadedFile {
  buffer: Buffer;
  originalName: string;
  mimeType: string;
}

/**
 * Inbound shape for POST /add/sub-category (RequestMapper.ADD_SUB_CATEGORY,
 * multipart/form-data, @ModelAttribute SubCategory). segmentId is required —
 * SubCategoryDAOController#createNewSubCategory unconditionally resolves
 * `entity.getSegmentId()` with no null-guard.
 */
export interface CreateSubCategoryInput {
  segmentId: number;
  name: string;
  metaTitle?: string;
  metaDescription?: string;
  /** NOT persisted — see schema-gap note above. Accepted for API-contract parity only. */
  avgWorkHoursPerMeter?: number | null;
  featured?: boolean;
  badgeProfileId?: number | null;
  madeToOrderProfileId?: number | null;
  volumeDiscountProfileId?: number | null;
  customSizeProfileId?: number | null;
  sizeProfileId?: number | null;
  finishProfileId?: number | null;
  fabricProfileId?: number | null;
  iconFile?: UploadedFile | null;
  socialImageFile?: UploadedFile | null;
  featuredImageFile?: UploadedFile | null;
}

/**
 * Inbound shape for PATCH /update/sub-category/{subCategoryId}
 * (RequestMapper.UPDATE_SUB_CATEGORY). Source
 * SubCategoryDAOController#updateSubCategory:
 *  - name, metaTitle, metaDescription, avgWorkHoursPerMeter, featured are
 *    always overwritten unconditionally (no null-guard in source).
 *  - segment is always re-resolved from segmentId unconditionally too.
 *  - each profile id is: left untouched if undefined/absent on the request,
 *    cleared to null if present-and-0, or re-resolved+set if present-and-nonzero.
 *  - each *File is only re-uploaded (and the old asset queued for deletion)
 *    if that specific file field is present on the request.
 */
export interface UpdateSubCategoryInput {
  id: number;
  segmentId: number;
  name: string;
  metaTitle?: string;
  metaDescription?: string;
  /** NOT persisted — see schema-gap note above. */
  avgWorkHoursPerMeter?: number | null;
  featured?: boolean;
  badgeProfileId?: number | null;
  madeToOrderProfileId?: number | null;
  volumeDiscountProfileId?: number | null;
  customSizeProfileId?: number | null;
  sizeProfileId?: number | null;
  finishProfileId?: number | null;
  fabricProfileId?: number | null;
  iconFile?: UploadedFile | null;
  socialImageFile?: UploadedFile | null;
  featuredImageFile?: UploadedFile | null;
}

/**
 * com.bloomscorp.loom.product.sub_category.orm.SubCategory — full entity
 * shape, as returned by retrieveSubCategory / retrieveSubCategoryById.
 * `avgWorkHoursPerMeter` / `impactConfigVersion` are always `null` /
 * `undefined` here — see schema-gap note above.
 */
export interface SubCategoryEntity {
  id: number;
  version: number;
  segmentId: number;
  name: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
  /** Always null — no backing column in the current schema (flagged above). */
  avgWorkHoursPerMeter: number | null;
  /** Always undefined — no backing column in the current schema (flagged above). */
  impactConfigVersion?: number;
  socialImage: string;
  featured: boolean;
  featuredImage: string;
  timeOfCreation: number;
  badgeProfileId: number | null;
  madeToOrderProfileId: number | null;
  volumeDiscountProfileId: number | null;
  customSizeProfileId: number | null;
  sizeProfileId: number | null;
  finishProfileId: number | null;
  fabricProfileId: number | null;
}

/**
 * com.bloomscorp.loom.product.sub_category.orm.SubCategoryPreview —
 * lightweight projection over the same `sub_category` table, excluding
 * profile relationships and featured-subcategory attributes (source class
 * doc: "minimizes query overhead" for navigation/menu use cases).
 */
export interface SubCategoryPreview {
  id: number;
  version: number;
  segmentId: number;
  name: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
  socialImage: string;
  timeOfCreation: number;
}

/**
 * com.bloomscorp.loom.product.sub_category.pojo.SubCategoryData — flat
 * projection returned by the table-explorer endpoints. Field order matches
 * the native query column order (source @ConstructorResult mapping;
 * preserved for parity, not required in TS). Note: no avgWorkHoursPerMeter /
 * impactConfigVersion — the Java native query itself omits them too.
 */
export interface SubCategoryData {
  id: number;
  version: number;
  segmentId: number;
  name: string;
  icon: string;
  metaTitle: string;
  metaDescription: string;
  socialImage: string;
  badgeProfileId: number | null;
  madeToOrderProfileId: number | null;
  volumeDiscountProfileId: number | null;
  customSizeProfileId: number | null;
  sizeProfileId: number | null;
  finishProfileId: number | null;
  fabricProfileId: number | null;
  timeOfCreation: number;
  featured: boolean;
  featuredImage: string;
}

/**
 * com.bloomscorp.loom.product.sub_category.pojo.FeaturedSubcategory —
 * result of the `findFeaturedSubCategories` named native query (joins
 * sub_category -> segment -> category, filtered by category name
 * case-insensitively and `featured = true`).
 */
export interface FeaturedSubcategory {
  segmentCategoryId: number;
  segmentCategoryName: string;
  subCategoryId: number;
  subCategoryName: string;
  subCategoryFeaturedImage: string;
}

/**
 * Cross-module dependencies SubCategoryDAOController calls into — Segment
 * (already migrated per the checkpoint, but its TS module wasn't part of
 * this upload batch, so it's ported as a port exactly like Cart's
 * FabricPreviewPort/etc. rather than guessing an unverified import path/API
 * shape), the seven Profile modules (not yet migrated), and S3 storage.
 * Narrow ports typed exactly to the calls SubCategory actually makes. Wire
 * real providers in SubCategory.module.ts as each dependency becomes
 * available.
 */
export interface SegmentPort {
  retrieveSegment(id: number): Promise<{ id: number } | null>;
}

/**
 * All seven profile lookups (badge / made-to-order / volume-discount /
 * custom-size / size / finish / fabric) share an identical shape in source —
 * each DAOController exposes a single `retrieve<X>Profile(id)` accessor that
 * SubCategoryDAOController calls the same way. One generic port interface,
 * seven distinct injection tokens.
 */
export interface ProfileLookupPort {
  retrieveEntity(id: number): Promise<{ id: number } | null>;
}

/**
 * com.bloomscorp.loom.image.service.S3StorageManagerService — the two
 * methods SubCategoryDAOController actually calls. `uploadImage` is typed to
 * accept `null` deliberately: source calls
 * `s3Store.uploadImage(entity.getIconFile())` / `...FeaturedImageFile())`
 * unconditionally on create, even when the corresponding MultipartFile is
 * null (field defaults to `""`, not `null`, so the source's own
 * `!= null` guard around featuredImage never actually stops the call) — see
 * SubCategory.mapper.ts for where this quirk is preserved.
 */
export interface S3StoragePort {
  uploadImage(file: UploadedFile | null): Promise<string>;
  initiateDeleteImageTask(url: string): Promise<void>;
}

export const SEGMENT_PORT = Symbol("SEGMENT_PORT");
export const BADGE_PROFILE_PORT = Symbol("BADGE_PROFILE_PORT");
export const MADE_TO_ORDER_PROFILE_PORT = Symbol("MADE_TO_ORDER_PROFILE_PORT");
export const VOLUME_DISCOUNT_PROFILE_PORT = Symbol("VOLUME_DISCOUNT_PROFILE_PORT");
export const CUSTOM_SIZE_PROFILE_PORT = Symbol("CUSTOM_SIZE_PROFILE_PORT");
export const SIZE_PROFILE_PORT = Symbol("SIZE_PROFILE_PORT");
export const FINISH_PROFILE_PORT = Symbol("FINISH_PROFILE_PORT");
export const FABRIC_PROFILE_PORT = Symbol("FABRIC_PROFILE_PORT");
export const S3_STORAGE_PORT = Symbol("S3_STORAGE_PORT");

/**
 * Log-message topics referenced by SubCategoryController /
 * SubCategoryPreviewController (source: com.bloomscorp.loom.support.LogMessage
 * — external, not present in this repository). Topic constant names ARE
 * source-verified from the controllers' static imports; exact prose is NOT
 * in this repository and is flagged, not invented.
 */
export const SubCategoryMessages = {
  UNAUTH_SUB_CATEGORY_REQUEST: "Unauthorized access to sub category.",
  UNAUTH_SUB_CATEGORY_CREATE_REQUEST: "Unauthorized attempt to create a sub category.",
  NEW_SUB_CATEGORY_CREATED: "Sub category created successfully.",
  UNAUTH_SUB_CATEGORY_UPDATE_REQUEST: "Unauthorized attempt to update a sub category.",
  SUB_CATEGORY_UPDATED: "Sub category updated successfully.",
  UNAUTH_SUB_CATEGORY_DELETE_REQUEST: "Unauthorized attempt to delete a sub category.",
  SUB_CATEGORY_DELETED: "Sub category deleted successfully.",
  UNAUTH_SUB_CATEGORY_LIST_REQUEST: "Unauthorized access to sub category list.",
  UNAUTH_TABLE_EXPLORER_SUB_CATEGORY_REQUEST: "Unauthorized access to table explorer sub category list.",
  UNAUTH_TABLE_EXPLORER_SUB_CATEGORY_BY_ID_REQUEST: "Unauthorized access to table explorer sub category by id.",
} as const;
