import { NextResponse } from "next/server";
import { readFileSync } from "fs";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// The Rebuild Map JSON is generated by the backend scanners at:
//   backend/rebuild-map/{status.json, loom-coverage.json}
// We read them by ABSOLUTE path (the wrapper backend and Weave live in the same
// anuprerna-rebuild tree) and return one merged, module-grouped view.
const BACKEND_DIR =
  process.env.BACKEND_SCRIPTS_DIR ||
  "/home/clawd/.openclaw/workspace/anuprerna-rebuild/backend";
const MAP_DIR = `${BACKEND_DIR}/rebuild-map`;

interface Endpoint {
  module: string;
  method: string;
  path: string;
  controllerClass: string;
  status: "native" | "passthrough";
  tested: boolean;
  lastVerified: string | null;
}

export async function GET() {
  try {
    const status = JSON.parse(
      readFileSync(`${MAP_DIR}/status.json`, "utf8"),
    ) as {
      generatedAt: string;
      test: { passed: number; failed: number; ok: boolean };
      totals: Record<string, number>;
      endpoints: Endpoint[];
    };
    const coverage = JSON.parse(
      readFileSync(`${MAP_DIR}/loom-coverage.json`, "utf8"),
    ) as { entities: { module: string; name: string }[] };

    const entByModule: Record<string, string[]> = {};
    for (const e of coverage.entities)
      (entByModule[e.module] ||= []).push(e.name);

    const byModule: Record<string, Endpoint[]> = {};
    for (const e of status.endpoints) (byModule[e.module] ||= []).push(e);

    const modules = Object.keys(byModule)
      .map((name) => {
        const eps = byModule[name]
          .slice()
          .sort(
            (a, b) =>
              a.path.localeCompare(b.path) || a.method.localeCompare(b.method),
          );
        const native = eps.filter((e) => e.status === "native").length;
        const tested = eps.filter((e) => e.tested).length;
        return {
          name,
          total: eps.length,
          native,
          tested,
          passthrough: eps.length - native,
          entities: entByModule[name] ?? [],
          endpoints: eps,
        };
      })
      .sort((a, b) => b.native - a.native || b.total - a.total || a.name.localeCompare(b.name));

    return NextResponse.json({
      generatedAt: status.generatedAt,
      test: status.test,
      totals: status.totals,
      moduleCount: modules.length,
      modules,
    });
  } catch (err) {
    return NextResponse.json(
      {
        error: "rebuild_map_unavailable",
        message: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }
}
