import {
  UserProfile,
  AddressItem,
  OrderListItem,
  OrderDetails,
  WholesaleMembershipInfo,
  WholesaleOrderInfo,
  NotificationPreference,
  NotificationActivityLog,
} from '@/types/domain/profile';

export const mockUserProfile: UserProfile = {
  tenant: {
    id: 10482,
    name: 'Ananya Sharma',
    email: 'ananya.sharma@designstudio.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
  },
};

export const mockAddresses: AddressItem[] = [
  {
    id: 1,
    addressType: 'SHIPPING',
    name: 'Ananya Sharma',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    addressLineOne: '42, Craft Lane, Indiranagar',
    addressLineTwo: 'Near 100 Feet Road',
    postalCode: '560038',
    companyName: 'Ananya Design Studio',
    primaryPhone: '+91 9876543210',
    secondaryPhone: '+91 80 25251122',
    contactEmail: 'ananya.sharma@designstudio.com',
    vatgstNumber: '29ABCDE1234F1Z5',
    primaryShippingAddress: true,
  },
  {
    id: 2,
    addressType: 'SHIPPING',
    name: 'Atelier Workshop',
    country: 'India',
    state: 'Maharashtra',
    city: 'Mumbai',
    addressLineOne: 'Suite 302, Textile Guild Building, Lower Parel',
    postalCode: '400013',
    primaryPhone: '+91 9820011223',
    contactEmail: 'workshop@ananyadesign.in',
    primaryShippingAddress: false,
  },
  {
    id: 3,
    addressType: 'BILLING',
    name: 'Ananya Sharma Design Pvt Ltd',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    addressLineOne: '42, Craft Lane, Indiranagar',
    addressLineTwo: '3rd Floor Office',
    postalCode: '560038',
    companyName: 'Ananya Sharma Design Pvt Ltd',
    primaryPhone: '+91 9876543210',
    contactEmail: 'accounts@ananyadesign.in',
    vatgstNumber: '29ABCDE1234F1Z5',
    eoriNumber: 'IN29ABCDE1234F1Z5',
    primaryBillingAddress: true,
  },
];

export const mockOrderList: OrderListItem[] = [
  {
    orderId: 'ORD-9021',
    orderType: 'ORDER',
    loyaltyOrder: true,
    status: 'PROCESSING',
    createdAt: Date.now() - 3600000 * 12, // 12 hours ago
    estimatedDeliveryDate: Date.now() + 86400000 * 4,
    totalItemCount: 3,
    processingItemCount: 2,
    readyItemCount: 1,
    dispatchedItemCount: 0,
    currency: 'INR',
    totalAmount: 18450.00,
  },
  {
    orderId: 'CO-4081',
    orderType: 'CUSTOM_ORDER',
    loyaltyOrder: true,
    status: 'PROCESSING',
    createdAt: Date.now() - 86400000 * 3,
    estimatedDeliveryDate: Date.now() + 86400000 * 6,
    totalItemCount: 2,
    processingItemCount: 2,
    readyItemCount: 2,
    dispatchedItemCount: 0,
    trackingUrl: 'https://track.courier.com/co4081',
    currency: 'INR',
    totalAmount: 34200.00,
  },
  {
    orderId: 'ORD-8812',
    orderType: 'ORDER',
    loyaltyOrder: false,
    status: 'DISPATCHED',
    dispatchedOn: '2026-07-28',
    createdAt: Date.now() - 86400000 * 5,
    estimatedDeliveryDate: Date.now() + 86400000 * 1,
    totalItemCount: 4,
    processingItemCount: 4,
    readyItemCount: 4,
    dispatchedItemCount: 4,
    trackingUrl: 'https://track.dhl.com/ORD8812',
    currency: 'INR',
    totalAmount: 26800.00,
  },
  {
    orderId: 'ORD-7620',
    orderType: 'ORDER',
    loyaltyOrder: false,
    status: 'CANCELLED',
    createdAt: Date.now() - 86400000 * 15,
    estimatedDeliveryDate: Date.now() - 86400000 * 10,
    totalItemCount: 1,
    currency: 'INR',
    totalAmount: 4200.00,
  },
];

export const mockSingleOrderDetails: OrderDetails = {
  id: 'ORD-9021',
  orderId: 'ORD-9021',
  createdAt: '2026-07-31T04:30:00.000Z',
  currency: 'INR',
  subTotal: 21000.00,
  shippingCost: 450.00,
  loyaltyOrder: true,
  loyaltyDiscountAmount: 3000.00,
  total: 18450.00,
  shippingMode: {
    name: 'Express Air Freight (Standard 3-5 Days)',
  },
  address: {
    shippingAddress: mockAddresses[0],
    billingAddress: mockAddresses[2],
  },
  fulfillments: [
    {
      id: 101,
      shippingCode: 'AWB-992104812',
      trackingUrl: 'https://track.bluedart.com/AWB992104812',
      dispatchedOn: '2026-07-30T10:00:00.000Z',
      estimatedDeliveryFrom: '2026-08-02',
      estimatedDeliveryTo: '2026-08-04',
      note: 'Shipment 1 of 2: In-Stock Handloom Cottons',
      fulfilledItems: [
        {
          id: 1,
          productName: 'Organic Handspun Khadi Cotton Fabric - Undyed Natural White',
          sku: 'KHD-WHT-001',
          quantity: 15,
          unit: 'Meters',
          heroImage: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=300&auto=format&fit=crop',
        },
      ],
    },
  ],
  items: [
    {
      id: 1,
      productId: 501,
      productName: 'Organic Handspun Khadi Cotton Fabric - Undyed Natural White',
      heroImage: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=300&auto=format&fit=crop',
      quantity: 15,
      unit: 'Meters',
      price: 450.00,
      orderCategory: 'IN_STOCK',
      orderStatus: 'DISPATCHED',
      paymentStatus: 'PAID',
      dispatchedOn: '2026-07-30',
      shippingCode: 'AWB-992104812',
      trackingUrl: 'https://track.bluedart.com/AWB992104812',
    },
    {
      id: 2,
      productId: 502,
      productName: 'Eri Silk Handwoven Fabric - Crimson Madder Dye',
      heroImage: 'https://images.unsplash.com/photo-1606760227091-3dd850d97f1d?q=80&w=300&auto=format&fit=crop',
      quantity: 10,
      unit: 'Meters',
      price: 1200.00,
      orderCategory: 'MADE_TO_ORDER',
      orderStatus: 'PROCESSING',
      paymentStatus: 'PAID',
      estimatedDeliveryTo: '2026-08-05',
    },
    {
      id: 3,
      productId: 503,
      productName: 'Jamdani Floral Motifs Handloom Cotton Scarf',
      heroImage: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=300&auto=format&fit=crop',
      quantity: 2,
      unit: 'Pieces',
      price: 1125.00,
      orderCategory: 'PRE_ORDER',
      orderStatus: 'INITIATED',
      paymentStatus: 'PAID',
      estimatedDeliveryTo: '2026-08-10',
    },
  ],
};

export const mockCustomOrderDetails: OrderDetails = {
  id: 'CO-4081',
  orderId: 'CO-4081',
  createdAt: '2026-07-28T09:15:00.000Z',
  currency: 'INR',
  subTotal: 32000.00,
  shippingCost: 800.00,
  loyaltyOrder: true,
  loyaltyDiscountAmount: 3200.00,
  adjustedTotal: 34200.00,
  total: 34200.00,
  shippingMode: {
    name: 'Custom Express Logistics',
  },
  address: {
    shippingAddress: mockAddresses[0],
    billingAddress: mockAddresses[2],
  },
  adjustments: [
    {
      particular: 'Custom Indigo Block Print Development Fee',
      adjustmentType: 1,
      adjustmentAmount: 3500.00,
      currency: 'INR',
    },
    {
      particular: 'Sample Swatch Credit Applied',
      adjustmentType: 2,
      adjustmentAmount: 2100.00,
      currency: 'INR',
    },
  ],
  fulfillments: [],
  items: [
    {
      id: 10,
      productId: 801,
      productName: 'Custom Hand-Dye Indigo Indigo Mulberry Silk Yardage (Custom Repeat 45cm)',
      heroImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=300&auto=format&fit=crop',
      quantity: 50,
      unit: 'Meters',
      price: 640.00,
      orderCategory: 'MADE_TO_ORDER',
      orderStatus: 'PROCESSING',
      paymentStatus: 'PAID',
      estimatedDeliveryTo: '2026-08-08',
    },
  ],
};

export const mockWholesaleMembershipInfo: WholesaleMembershipInfo = {
  active: true,
  programEnrollmentDateEpochMS: Date.now() - 86400000 * 365,
  currentCycleStartDateEpochMS: Date.now() - 86400000 * 120,
  currentCycleEndDateEpochMS: Date.now() + 86400000 * 245,
  percentileDiscount: 15,
  minimumOrderValue: 25000,
  minimumOrderValueCurrency: 'INR',
};

export const mockWholesaleOrderInfo: WholesaleOrderInfo = {
  totalAbsoluteDiscount: 48500.00,
  totalOrderCount: 14,
  averageOrderValue: 36200.00,
  percentileUtilization: 88,
};

export const mockNotificationPreferences: NotificationPreference[] = [
  {
    id: 'order_status',
    title: 'Order Status & Dispatch Alerts',
    description: 'Receive real-time notifications when your order is confirmed, packed, and out for delivery.',
    enabled: true,
  },
  {
    id: 'artisan_story',
    title: 'Artisan & Craft Progress Updates',
    description: 'Get exclusive photo and video updates directly from loom artisans working on your orders.',
    enabled: true,
  },
  {
    id: 'wholesale_alerts',
    title: 'Wholesale Savings & Tier Alerts',
    description: 'Notifications regarding your wholesale tier status, threshold milestones, and special partner pricing.',
    enabled: true,
  },
  {
    id: 'promotional_offers',
    title: 'New Collection & Swatch Drops',
    description: 'Be the first to know when new seasonal artisan fabrics and limited swatches become available.',
    enabled: false,
  },
];

export const mockNotificationLogs: NotificationActivityLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-07-31 10:15 AM',
    action: 'Consent Confirmed',
    details: 'WhatsApp notifications active for +91 9876543210 (Valid for 1 Year)',
  },
  {
    id: 'log-2',
    timestamp: '2026-07-30 02:45 PM',
    action: 'Message Sent',
    details: 'Dispatch update sent for Order #ORD-9021 (AWB-992104812)',
  },
  {
    id: 'log-3',
    timestamp: '2026-07-28 11:00 AM',
    action: 'Preference Updated',
    details: 'Enabled Wholesale Savings & Tier Alerts',
  },
];
