// @ts-nocheck
export const FAQ_MESSAGES = {
    UNAUTH_FAQ_LIST_REQUEST: "UNAUTH_FAQ_LIST_REQUEST",
    UNAUTH_FAQ_REQUEST: "UNAUTH_FAQ_REQUEST",
    UNAUTH_FAQ_CREATE_REQUEST: "UNAUTH_FAQ_CREATE_REQUEST",
    NEW_FAQ_CREATED: "NEW_FAQ_CREATED",
    UNAUTH_FAQ_UPDATE_REQUEST: "UNAUTH_FAQ_UPDATE_REQUEST",
    FAQ_UPDATED: "FAQ_UPDATED",
    UNAUTH_TABLE_EXPLORER_FAQ_REQUEST: "UNAUTH_TABLE_EXPLORER_FAQ_REQUEST",
    UNAUTH_TABLE_EXPLORER_FAQ_QUESTION_BY_ID_REQUEST: "UNAUTH_TABLE_EXPLORER_FAQ_QUESTION_BY_ID_REQUEST",
    UNAUTH_TABLE_EXPLORER_FAQ_QUESTION_REQUEST: "UNAUTH_TABLE_EXPLORER_FAQ_QUESTION_REQUEST",
    UNAUTH_TABLE_EXPLORER_FAQ_BY_ID_REQUEST: "UNAUTH_TABLE_EXPLORER_FAQ_BY_ID_REQUEST"
};

// Port token for cross-module dependency if needed
export const BLOG_CONTENT_SERVICE = Symbol("BLOG_CONTENT_SERVICE");
export const STORY_CONTENT_SERVICE = Symbol("STORY_CONTENT_SERVICE");
// @ts-nocheck
// @ts-nocheck
